# ============================== application-xml.properties =====================================
# application-xml.properties à toujours mettre dans src/main/resources/ et PAS
# dans src/test/resources/

###################################################################
# MODE DE STOCKAGE - XML
###################################################################
