# ============================== application-xml.properties =====================================
# application-xml.properties à toujours mettre dans src/main/resources/ et PAS
# dans src/test/resources/

###################################################################
# MODE DE STOCKAGE - ADAPTER XML DE SORTIE
###################################################################
# Pas de DataSource ici. La DataSource dépend de l'environnement d'exécution (TEST, DEV, PROD)
