# ===== application-desktop.properties ====
############################################
# MODE D'ACCES DESKTOP
############################################
# Ce properties ne sert qu'à choisir le mode d'accès DESKTOP
# Pas de DataSource (qui dépend de l'environnement d'exécution TEST, DEV, PROD, ...) ici

# Activation du profil SPRING DESKTOP
spring.config.activate.on-profile=desktop

# désactivation de JMX avec JavaFX via le application.properties
spring.jmx.enabled=false
