# ===== application-web.properties ====
############################################
# MODE D'ACCES WEB
############################################
# Ce properties ne sert qu'à choisir le mode d'accès WEB
# Pas de DataSource (qui dépend de l'environnement d'exécution) ici

# démarrage du serveur Tomcat
spring.main.web-application-type=servlet

# Port HTTP
server.port=8080
