# ============================== application-jpa.properties =====================================
# application-jpa.properties à toujours mettre dans src/main/resources/ et PAS
# dans src/test/resources/

###################################################################
# MODE DE STOCKAGE - ADAPTER JPA DE SORTIE
###################################################################
# Pas de DataSource ici. La DataSource dépend de l'environnement d'exécution (TEST, DEV, PROD)
